// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Contrib.Avro.CodeGen.Tests
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class MessageWithLogicalDecorators2 : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""MessageWithLogicalDecorators"",""namespace"":""Contrib.Avro.CodeGen.Tests"",""fields"":[{""name"":""Id"",""type"":{""type"":""string"",""logicalType"":""uuid"",""logicalTypeHint"":""user-id""}},{""name"":""createdBy"",""type"":[""null"",{""type"":""string"",""logicalType"":""uuid"",""logicalTypeHint"":""user-id""}]},{""name"":""decoratedInChoice"",""type"":[""int"",{""type"":""string"",""logicalType"":""uuid"",""logicalTypeHint"":""user-id""}]}]}");
		private System.Guid _Id;
		private System.Nullable<System.Guid> _createdBy;
		private object _decoratedInChoice;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return MessageWithLogicalDecorators._SCHEMA;
			}
		}
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				this._Id = value;
			}
		}
		public System.Nullable<System.Guid> createdBy
		{
			get
			{
				return this._createdBy;
			}
			set
			{
				this._createdBy = value;
			}
		}
		public object decoratedInChoice
		{
			get
			{
				return this._decoratedInChoice;
			}
			set
			{
				this._decoratedInChoice = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Id;
			case 1: return this.createdBy;
			case 2: return this.decoratedInChoice;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Id = (System.Guid)fieldValue; break;
			case 1: this.createdBy = (System.Nullable<System.Guid>)fieldValue; break;
			case 2: this.decoratedInChoice = (System.Object)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
